import Header from "@/components/Header";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/permissions";
import { changePasswordAction, deleteAccountAction, unblockCreatorAction, updateAccountNameAction } from "./actions";

export default async function AccountPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const user = await requireUser(); const query = await searchParams;
  const blocks = await db.creatorBlock.findMany({ where: { userId: user.id }, include: { creator: { select: { id: true, displayName: true, username: true } } }, orderBy: { createdAt: "desc" } });
  return <><Header/><main><section className="page-title"><span className="badge">CONTA</span><h1>Minha conta</h1><p>Dados pessoais, segurança e privacidade.</p></section>{query.success ? <div className="success-banner">Alteração concluída com sucesso.</div> : null}{query.error ? <div className="error-banner">Não foi possível concluir. Verifique os dados introduzidos.</div> : null}<div className="account-grid"><section className="card"><h2>Dados pessoais</h2><p className="muted">Email: {user.email}</p><form action={updateAccountNameAction} className="form"><label>Nome<input name="name" defaultValue={user.name ?? ""} minLength={2} maxLength={80} required/></label><button className="btn primary">Guardar nome</button></form></section><section className="card"><h2>Alterar palavra-passe</h2><form action={changePasswordAction} className="form"><label>Palavra-passe atual<input name="currentPassword" type="password" required/></label><label>Nova palavra-passe<input name="newPassword" type="password" minLength={12} required/></label><label>Confirmar nova palavra-passe<input name="confirmation" type="password" minLength={12} required/></label><button className="btn primary">Alterar palavra-passe</button></form></section></div><section className="card account-section"><h2>Criadores bloqueados</h2>{blocks.length === 0 ? <p className="muted">Não bloqueou nenhum criador.</p> : <div className="billing-list">{blocks.map(({ creator }) => <article key={creator.id}><div><strong>{creator.displayName}</strong><span>@{creator.username}</span></div><form action={unblockCreatorAction}><input type="hidden" name="creatorId" value={creator.id}/><button className="btn secondary">Desbloquear</button></form></article>)}</div>}</section><section className="card account-section"><h2>Cópia dos seus dados</h2><p className="muted">Descarregue um ficheiro JSON com os dados principais da sua conta.</p><a className="btn secondary" href="/api/account/export">Descarregar dados</a></section><section className="danger-zone"><h2>Eliminar conta</h2><p>Esta ação é permanente. Publicações, favoritos, seguimentos e restantes dados associados serão eliminados.</p>{user.role === "ADMIN" ? <p className="muted">A conta administrativa principal não pode ser eliminada aqui.</p> : <form action={deleteAccountAction} className="form"><label>Palavra-passe<input name="password" type="password" required/></label><label>Escreva ELIMINAR<input name="confirmation" autoComplete="off" required/></label><button className="btn danger">Eliminar definitivamente</button></form>}</section></main></>;
}
