import Header from "@/components/Header";
import { money } from "@/lib/billing";
import { db } from "@/lib/db";
import { requireAdmin } from "@/lib/permissions";
import { createAccessCodeAction, disableAccessCodeAction, grantPremiumAccessAction, revokePremiumAccessAction } from "./actions";

export default async function AdminBillingPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  await requireAdmin();
  const params = await searchParams;
  const [subscriptions, payments, earnings, accessCodes, blockedAttempts] = await Promise.all([
    db.subscription.findMany({ include: { subscriber: { select: { email: true } }, creator: { select: { displayName: true } }, plan: true }, orderBy: { createdAt: "desc" }, take: 100 }),
    db.payment.findMany({ orderBy: { createdAt: "desc" }, take: 100 }),
    db.creatorEarning.findMany({ include: { creator: { select: { displayName: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
    db.accessCode.findMany({ include: { _count: { select: { redemptions: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
    db.securityEvent.count({ where: { success: false, createdAt: { gte: new Date(Date.now() - 24 * 60 * 60 * 1000) } } }),
  ]);
  const gross = payments.filter((item) => item.status === "SUCCEEDED").reduce((sum, item) => sum + item.amountMinor, 0);
  const creatorNet = earnings.filter((item) => item.status !== "REVERSED").reduce((sum, item) => sum + item.netAmountMinor, 0);
  return <><Header/><main className="page-shell"><section className="page-title"><span className="badge">ADMIN · FATURAÇÃO</span><h1>Assinaturas e pagamentos</h1><p>Registos recebidos do fornecedor. Nenhum dado de cartão é armazenado.</p></section>
    {params.success ? <div className="success-banner">Operação concluída.</div> : null}{params.error ? <div className="error-banner">Não foi possível concluir. Confirme os dados e tente novamente.</div> : null}
    <div className="stats"><div><strong>{subscriptions.filter((item) => item.status === "ACTIVE").length}</strong><span>Assinaturas ativas</span></div><div><strong>{payments.filter((item) => item.status === "SUCCEEDED").length}</strong><span>Pagamentos concluídos</span></div><div><strong>{blockedAttempts}</strong><span>Tentativas falhadas (24h)</span></div><div><strong>{money(creatorNet, "USD")}</strong><span>Atribuído a criadores</span></div></div>
    <div className="admin-billing-tools"><section className="billing-section"><h2>Conceder Premium</h2><p className="muted">Ative ou prolongue o acesso gratuito de um utilizador.</p><form action={grantPremiumAccessAction} className="stack-form"><label>Email<input name="email" type="email" required/></label><label>Duração<select name="durationDays" defaultValue="30"><option value="7">7 dias</option><option value="14">14 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></label><button className="btn primary">Conceder acesso</button></form></section>
    <section className="billing-section"><h2>Criar código</h2><p className="muted">O código não poderá ser recuperado depois; guarde apenas o valor que escrever.</p><form action={createAccessCodeAction} className="stack-form"><label>Código<input name="code" pattern="[A-Za-z0-9-]{6,40}" placeholder="MOZ-TESTE-30" required/></label><label>Identificação interna<input name="label" maxLength={80} placeholder="Campanha de teste" required/></label><label>Acesso<select name="durationDays" defaultValue="30"><option value="7">7 dias</option><option value="14">14 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></label><label>Utilizações máximas<input name="maxRedemptions" type="number" min="1" max="100" defaultValue="1" required/></label><label>Validade do código<select name="expiresInDays" defaultValue="30"><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></label><button className="btn primary">Criar código</button></form></section></div>
    <section className="billing-section"><h2>Códigos de acesso</h2>{accessCodes.length === 0 ? <p className="muted">Nenhum código criado.</p> : <div className="billing-list">{accessCodes.map((code) => <article key={code.id}><div><strong>{code.label}</strong><span>{code.durationDays} dias · {code._count.redemptions}/{code.maxRedemptions} utilizações · expira {code.expiresAt?.toLocaleDateString("pt-PT") ?? "sem prazo"}</span></div><div><span className={`status-pill status-${code.active ? "active" : "canceled"}`}>{code.active ? "ATIVO" : "DESATIVADO"}</span>{code.active ? <form action={disableAccessCodeAction}><input type="hidden" name="codeId" value={code.id}/><button className="btn secondary">Desativar</button></form> : null}</div></article>)}</div>}</section>
    <section className="billing-section"><h2>Assinaturas recentes</h2>{subscriptions.length === 0 ? <p className="muted">Sem assinaturas.</p> : <div className="billing-list">{subscriptions.map((item) => <article key={item.id}><div><strong>{item.subscriber.email}</strong><span>{item.creator?.displayName ?? item.plan.name} · {item.provider} · até {item.currentPeriodEnd?.toLocaleDateString("pt-PT") ?? "sem prazo"}</span></div><div><span className={`status-pill status-${item.status.toLowerCase()}`}>{item.status}</span><strong>{item.provider === "MANUAL" ? "Gratuito" : money(item.plan.amountMinor, item.plan.currency)}</strong>{item.status === "ACTIVE" && item.type === "PLATFORM_PREMIUM" ? <form action={revokePremiumAccessAction}><input type="hidden" name="subscriptionId" value={item.id}/><button className="btn secondary">Revogar</button></form> : null}</div></article>)}</div>}</section>
    <section className="billing-section"><h2>Ganhos de criadores</h2>{earnings.length === 0 ? <p className="muted">Sem ganhos registados.</p> : <div className="billing-list">{earnings.map((item) => <article key={item.id}><div><strong>{item.creator.displayName}</strong><span>Bruto {money(item.grossAmountMinor, item.currency)} · taxa {money(item.platformFeeMinor, item.currency)}</span></div><div><span className={`status-pill status-${item.status.toLowerCase()}`}>{item.status}</span><strong>{money(item.netAmountMinor, item.currency)}</strong></div></article>)}</div>}</section>
  </main></>;
}
